version: "3.7"

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.1
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: elastic-dev
      ELASTICSEARCH_PASSWORD: admin
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elastic
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

networks:
  elastic:
    driver: bridge