version: "3.7"

services:
  elasticsearch:
    container_name: elasticsearch-service
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  kibana:
    container_name: kibana-service
    image: docker.elastic.co/kibana/kibana:8.4.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601