export enum PoliticianMapping {
  fullName = 'NOMBRE',
  party = 'PARTIDO',
  partyFilter = 'PARTIDO_PARA_FILTRO',
  gender = 'GENERO',
  occupation = 'CARGO',
  occupationFilter = 'CARGO_PARA_FILTRO',
  community = 'CCAA',
  institution = 'INSTITUCION',
  baseSalary = 'SUELDOBASE_SUELDO',
  monthlyPayment = 'RETRIBUCIONMENSUAL',
  yearlyPayment = 'RETRIBUCIONANUAL',
  complementSalary = 'COMPLEMENTOS_SUELDO',
  extraPay = 'PAGASEXTRA_SUELDO',
  otherAllowancesAndIndemnities = 'OTRASDIETASEINDEMNIZACIONES_SUELDO',
  threeYearsSalary = 'TRIENIOS_SUELDO',
  observations = 'Dedicación Exclusiva',
}
